---
title: "Artículo 1: Redes bayesianas multinomiales"
author: "Vidal López A01253568"
format:
   html:
     toc: true
     html-math-method: katex
     embed-resources: true
     self-contained-math: true
     df-print: kable
editor: source
---

## Artículo 1: Redes bayesianas multinomiales

# Librerias usadas

```{r}
library(tidyverse)
library(bnlearn)
```

```{r}
getwd()
```

# Cargando y creando la base de datos optima

```{r}
viaje <- read_csv("data/eod_2017/tviaje_eod2017/conjunto_de_datos/tviaje.csv") %>%
  select(id_soc, p5_3, p5_6, p5_7_7, p5_14_01, p5_14_07, p5_14_12, p5_14_14, p5_14_19, p5_14_20) %>%
  mutate(across(everything(), as.factor))  # Convertir todo a factor

dem <- read_csv("data/eod_2017/tsdem_eod2017/conjunto_de_datos/tsdem.csv") %>%
  select(id_soc, sexo, edad, ent, niv) %>%
  mutate(across(everything(), as.factor))
```

```{r}
# Unir las tablas por id_soc
base_final <- viaje %>%
  left_join(dem, by = "id_soc")
```

```{r}
head(base_final)
```

```{r}
sum(is.na(base_final))
```

# Generando DAGS

DAG_1

```{r}
colnames(base_final) = c("id_soc", "p5_3", "p5_6", "p5_7_7", "p5_14_01", "p5_14_07", "p5_14_12", "p5_14_14", "p5_14_19", "p5_14_20", "sexo", "edad", "ent", "niv")
```

```{r}
dag_1 = empty.graph(nodes = c("sexo", "edad", "niv", "ent", "p5_3", "p5_6", "p5_7_7", 
                             "p5_14_01", "p5_14_07", "p5_14_12", "p5_14_14", "p5_14_19", "p5_14_20"))

arc_set = matrix(c(
  'sexo', 'p5_3',
  'edad', 'p5_3', 
  'niv', 'p5_3',
  
  'sexo', 'p5_6',
  'edad', 'p5_6',
  'niv', 'p5_6',
  'ent', 'p5_6',
  
  'sexo', 'p5_7_7',
  'edad', 'p5_7_7',
  'niv', 'p5_7_7',
  'ent', 'p5_7_7',
  
  'p5_3', 'p5_14_01',
  'p5_6', 'p5_14_01',
  'p5_7_7', 'p5_14_01',
  
  'p5_3', 'p5_14_07',
  'p5_6', 'p5_14_07',
  'p5_7_7', 'p5_14_07',
  
  'p5_3', 'p5_14_12',
  'p5_6', 'p5_14_12',
  'p5_7_7', 'p5_14_12',
  
  'p5_3', 'p5_14_14',
  'p5_6', 'p5_14_14',
  'p5_7_7', 'p5_14_14',
  
  'p5_3', 'p5_14_19',
  'p5_6', 'p5_14_19',
  'p5_7_7', 'p5_14_19',
  
  'p5_3', 'p5_14_20',
  'p5_6', 'p5_14_20',
  'p5_7_7', 'p5_14_20'
  
), byrow = TRUE, ncol = 2,
dimnames = list(NULL, c("from", "to")))

print(arc_set)

arcs(dag_1) = arc_set
```

```{r}
# Verify the structure
dag_1
```


DAG_2

```{r}
dag_2 = model2network("[sexo][edad][p5_3][ent][p5_6|ent][niv|sexo:edad][p5_7_7|p5_6][p5_14_01|p5_3:sexo:niv:p5_7_7][p5_14_07|p5_3:sexo:niv:p5_7_7][p5_14_12|p5_3:sexo:niv:p5_7_7][p5_14_14|p5_3:sexo:niv:p5_7_7][p5_14_19|p5_3:sexo:niv:p5_7_7][p5_14_20|p5_3:sexo:niv:p5_7_7]")
```

```{r}
dev.new(width=12, height=8)  
graphviz.plot(dag_2, shape = "ellipse")
```

```{r}
dag_2
```
DAG_3

```{r}
dag_3 = model2network("[sexo][edad][ent][niv|sexo:edad:ent][p5_7_7|ent][p5_6|p5_7_7][p5_3|niv:p5_6][p5_14_01|p5_3][p5_14_07|p5_3][p5_14_12|p5_3][p5_14_14|p5_3][p5_14_19|p5_3][p5_14_20|p5_3]")
```

```{r}
dev.new(width=12, height=8)  
graphviz.plot(dag_3, shape = "ellipse")
```
```{r}
dag_3
```

best_dag

```{r}
base_df <- as.data.frame(base_final[, -1]) %>%
  mutate(across(where(is.factor), droplevels))
best_dag = hc(base_df)
```

```{r}
best_dag
```

```{r}
dev.new(width=12, height=8)  
graphviz.plot(best_dag, shape = "ellipse")
```

Scores de cada una de las DAGs

```{r}
base_df <- as.data.frame(base_final[, -1]) %>%
  mutate(across(where(is.factor), droplevels))
score(dag_1, data = base_df, type = "bic")
score(dag_1, data = base_df, type = "aic")
```

```{r}
base_df <- as.data.frame(base_final[, -1]) %>%
  mutate(across(where(is.factor), droplevels))
score(dag_2, data = base_df, type = "bic")
score(dag_2, data = base_df, type = "aic")
```

```{r}
base_df <- as.data.frame(base_final[, -1]) %>%
  mutate(across(where(is.factor), droplevels))
score(dag_3, data = base_df, type = "bic")
score(dag_3, data = base_df, type = "aic")
```

```{r}
base_df <- as.data.frame(base_final[, -1]) %>%
  mutate(across(where(is.factor), droplevels))
score(best_dag, data = base_df, type = "bic")
score(best_dag, data = base_df, type = "aic")
```

